In [7]:
import numpy as np

# Path to your .npy file
file_path = "russell3000_covariance.npy"

# Load the .npy file
data = np.load(file_path)

print(data.size)

# Print the contents of the file
print(data)

28224
[[6.37431870e-04 1.18183506e-04 8.49994346e-05 ... 7.14261641e-05
  1.76262037e-04 2.13752671e-04]
 [1.18183506e-04 1.65217246e-03 3.24759769e-05 ... 2.31875192e-05
  7.60443548e-05 8.47760873e-05]
 [8.49994346e-05 3.24759769e-05 1.87344503e-04 ... 1.13556305e-04
  7.49570060e-05 7.26144390e-05]
 ...
 [7.14261641e-05 2.31875192e-05 1.13556305e-04 ... 2.09081126e-04
  6.94813859e-05 6.80986407e-05]
 [1.76262037e-04 7.60443548e-05 7.49570060e-05 ... 6.94813859e-05
  2.45924338e-04 1.20850524e-04]
 [2.13752671e-04 8.47760873e-05 7.26144390e-05 ... 6.80986407e-05
  1.20850524e-04 5.91245257e-04]]


In [9]:
import numpy as np

# Path to your .npy file
file_path = "russell3000_correlation.npy"

# Load the .npy file
data = np.load(file_path)

print(data.size)

# Print the contents of the file
print(data)

28224
[[1.         0.11516282 0.24596804 ... 0.19565143 0.44518563 0.34818562]
 [0.11516282 1.         0.05837327 ... 0.03945201 0.11929948 0.08577522]
 [0.24596804 0.05837327 1.         ... 0.57376408 0.34921348 0.21818188]
 ...
 [0.19565143 0.03945201 0.57376408 ... 1.         0.3064152  0.19368554]
 [0.44518563 0.11929948 0.34921348 ... 0.3064152  1.         0.31693044]
 [0.34818562 0.08577522 0.21818188 ... 0.19368554 0.31693044 1.        ]]


In [10]:
import numpy as np

# Path to your .npy file
file_path = "russell3000_returns.npy"

# Load the .npy file
data = np.load(file_path)

print(data.size)

# Print the contents of the file
print(data)

1815912
[[-0.00904968 -0.05494505  0.00699301 ...  0.01704545 -0.02552219
  -0.01239666]
 [ 0.          0.12790698  0.         ...  0.          0.00952381
  -0.00418434]
 [ 0.01826478  0.05154639  0.01388889 ...  0.02793296 -0.00471698
  -0.01050405]
 ...
 [-0.05898681  0.01855562 -0.01602241 ... -0.00726282 -0.04473684
  -0.02880658]
 [ 0.07743368 -0.01378626  0.04531997 ...  0.05334553  0.01469238
   0.05508475]
 [ 0.08738302 -0.00099853 -0.01982571 ... -0.02344089  0.03122172
   0.03279786]]
